spring:
  datasource:
    url: jdbc:mysql://localhost/demo?serverTimezone=CET
    username: oms
    password: oms
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always # it will always execute the script 'schema.sql' and 'data.sql' on the resource folder
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.springframework.transaction: trace


